version: "3.7"

services:
    server:
        build:
            context: ./
            target: development-build-stage
        ports:
            - "5000:5000"
        volumes:
            - ./:/app
            - /app/node_modules
        restart: "unless-stopped"
        networks:
            - backend
        depends_on:
            - mysql

    mysql:
      build: ./docker/mysql
      volumes:
        - ./docker/data/mysql:/var/lib/mysql
      environment:
        MYSQL_ROOT_PASSWORD: db
        MYSQL_DATABASE: db
        MYSQL_USER: db
        MYSQL_PASSWORD: db
      expose:
        - "3306"
      ports:
        - "127.0.0.1:4506:3306"
      command: "mysqld --innodb-flush-method=fsync"
      
    mysql_test:
      build: ./docker/mysql
      tmpfs:
        - /var/lib/mysql
      environment:
        MYSQL_ROOT_PASSWORD: db
        MYSQL_DATABASE: db
        MYSQL_USER: db
        MYSQL_PASSWORD: db
      expose:
        - "3306"
      ports:
        - "127.0.0.1:4507:3306"
      command: "mysqld --innodb-flush-method=fsync"

networks:
    backend:
        driver: bridge
